### PR TITLE
update all links to GHES instead of GHEC@latest

### PR DESCRIPTION
**Pull request by felickz**
Update GHEC@latest links to GHES 

ex:

```diff
- * [Secret scanning documentation](https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/about-secret-scanning)
+ * [Secret scanning documentation](https://docs.github.com/en/enterprise-server/code-security/secret-scanning/about-secret-scanning)
```

### CODE REVIEW

**Review by felickz — COMMENTED** [review]
- [x] i have clicked all the links and validated they all work... and redirect to the latest version (currently 3.9 ... `/enterprise-server@3.9/` )

**Comment by leftrightleft** [comment]
🙏 You are a saint

**Review by leftrightleft — APPROVED** [review]
👍

**Comment by leftrightleft** [comment]
@felickz shoot looks like there's a conflict :(

**Pull request merged**
